# Compile Nginx for Ubuntu16.04
FROM ubuntu:16.04

RUN apt update
RUN apt upgrade -y
RUN apt install -y \
	build-essential \
	wget
RUN wget https://nginx.org/download/nginx-1.13.7.tar.gz && tar zxvf nginx-1.13.7.tar.gz && \
	wget https://ftp.pcre.org/pub/pcre/pcre-8.40.tar.gz && tar xzvf pcre-8.40.tar.gz && \
	wget http://www.zlib.net/zlib-1.2.11.tar.gz && tar xzvf zlib-1.2.11.tar.gz && \
	wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz && tar xzvf openssl-1.1.0f.tar.gz

WORKDIR /nginx-1.13.7
RUN ./configure --prefix=/usr/share/nginx \
	            --sbin-path=/usr/sbin/nginx \
	            --modules-path=/usr/lib/nginx/modules \
	            --conf-path=/etc/nginx/nginx.conf \
	            --error-log-path=/var/log/nginx/error.log \
	            --http-log-path=/var/log/nginx/access.log \
	            --pid-path=/run/nginx.pid \
	            --lock-path=/var/lock/nginx.lock \
	            --user=www-data \
	            --group=www-data \
	            --build=Ubuntu \
	            --http-client-body-temp-path=/var/lib/nginx/body \
	            --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
	            --http-proxy-temp-path=/var/lib/nginx/proxy \
	            --http-scgi-temp-path=/var/lib/nginx/scgi \
	            --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
	            --with-openssl=../openssl-1.1.0f \
	            --with-openssl-opt=enable-ec_nistp_64_gcc_128 \
	            --with-openssl-opt=no-nextprotoneg \
	            --with-openssl-opt=no-weak-ssl-ciphers \
	            --with-openssl-opt=no-ssl3 \
	            --with-pcre=../pcre-8.40 \
	            --with-pcre-jit \
	            --with-zlib=../zlib-1.2.11 \
	            --with-compat \
	            --with-file-aio \
	            --with-threads \
	            --with-http_addition_module \
	            --with-http_auth_request_module \
	            --with-http_dav_module \
	            --with-http_flv_module \
	            --with-http_gunzip_module \
	            --with-http_gzip_static_module \
	            --with-http_mp4_module \
	            --with-http_random_index_module \
	            --with-http_realip_module \
	            --with-http_slice_module \
	            --with-http_ssl_module \
	            --with-http_sub_module \
	            --with-http_stub_status_module \
	            --with-http_v2_module \
	            --with-http_secure_link_module \
	            --with-mail \
	            --with-mail_ssl_module \
	            --with-stream \
	            --with-stream_realip_module \
	            --with-stream_ssl_module \
	            --with-stream_ssl_preread_module \
	            --with-debug \
	            --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' \
	            --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' && \
	make && \
	checkinstall --install=no 

RUN mkdir /package

VOLUME /package
RUN cp *.deb /package/.
